apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-istio
data:
  APP_CLIENT_HOST: backend-istio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-istio
  labels:
    app: bff-istio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-istio
  template:
    metadata:
      labels:
        app: bff-istio
    spec:
      containers:
      - name: bff-istio
        image: arqt-istio/bff-istio:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 300m
            memory: 130Mi
          limits:
            cpu: 600m
            memory: 290Mi
        envFrom:
        - configMapRef:
            name: bff-istio
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: health
          containerPort: 8081
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: health
          initialDelaySeconds: 5
          periodSeconds: 2
        startupProbe:
          httpGet:
            path: /actuator/health
            port: health
          failureThreshold: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: health
          initialDelaySeconds: 7
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bff-istio
  labels:
    app: bff-istio
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: bff-istio
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bff-external-route
spec:
  hosts:
  - bff.apps.{{CLUSTER_IP}}.nip.io
  gateways:
  - istio-system/ingressgateway
  http:
  - route:
    - destination:
        host: bff-istio
