logging:
  level:
    root: error
    br.com.votorantim: info
management:
  server:
    port: 8081
  metrics:
    export:
      jmx:
        enabled: false
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
app.client:
  host: localhost
  port: 80